/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import domain.Car;
import file.CarFile;
import java.io.File;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Melissa Ramírez R
 */
public class InterfaceTable extends javax.swing.JInternalFrame {
Car car = new Car();
    File file = new File("./carFinal.dat");
    /**
     * Creates new form InterfaceTable
     */
    public InterfaceTable() {
        initComponents();
        arrayList();
    }

    public void arrayList() {
        RandomAccessFile randomAccessFile;

        try {

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            CarFile carFile = new CarFile(file);
            ArrayList<Car> arrayCar = carFile.getCarList();
            Object car[] = new Object[5];
            // randomAccessFile = new RandomAccessFile(file, "rw");

            //int regsQuantity = (int) Math.ceil((double) randomAccessFile.length() / (double) 150);
            //se pone en arrayCarsize porque el regsQuantity toma hasta los que  
            for (int i = 0; i < arrayCar.size(); i++) {
                car[0] = arrayCar.get(i).getName();
                car[1] = arrayCar.get(i).getYear();
                car[2] = arrayCar.get(i).getMileage();
                car[3] = arrayCar.get(i).isAmerican();
                car[4] = arrayCar.get(i).getSerial();
                model.addRow(car);
            }

        } catch (IOException ex) {
            System.out.println("Problemas con el archivo btn ingresar");
        }

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbv_tableActualizaSerie1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setTitle("Vehiculos Registrados");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Marca", "Año", "Kilometraje", "Americano", "Serie"
            }
        ));
        tbv_tableActualizaSerie1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbv_tableActualizaSerie1, javax.swing.GroupLayout.DEFAULT_SIZE, 834, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(tbv_tableActualizaSerie1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable jTable1;
    private javax.swing.JScrollPane tbv_tableActualizaSerie1;
    // End of variables declaration//GEN-END:variables
}
